config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'sessions#home'

  get '/art_works/title' => 'art_works#title', as: 'title'

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#facebook_login'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'



  resources :art_works do
    resources :comments
  end

  resource :comments, :only => [:update, :destroy, :create]


  # resources :challenges do
  #   resources :art_works, shallow: true
  # end

  resources :challenges do
    resources :art_works
  end

  resources :users do
    resources :art_works
  end
  
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    has_many :art_works
    has_many :users, through: :art_works
    
    scope :alpha, -> {order(:name)}

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

    def index
        @challenges = Challenge.all.alpha
    end

    # def new
    #     @challenge = Challenge.new
    # end

    # def create
    # end

    def show
        @challenge = Challenge.find_by(id: params[:id])
    end

    private

    def challenge_params
        params.require(:challenge).permit(:name, :instructions, :image, :art_work_id)
    end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/index.html.erb
<div class="container" style="padding-top:60px">
  <%# link_to "Make a New Challenge", new_challenge_path %>

  <% @challenges.each do |c| %>
    <div class="container">
      <h2><%= link_to c.name, challenge_path(c) %></h2>
    </div>
  <% end %>
</div>

app/views/challenges/show.html.erb
<!-- <div class="row justify-content-center align-items-center" style="padding-top:60px"> -->
<div class="container" style="padding-top:60px; padding-bottom:60px">

  <div class="col-nd-4 text-center">
    <h1><%= @challenge.name %></h1>
    <p>Total Submissions: <%= @challenge.art_works.count %> </p>
    <p>challenge instructions here</p>
    <%= link_to "Submit Your Work", new_challenge_art_work_path(@challenge), class: 'btn btn-primary' %>
    <br><br>
  </div>



    <div class="card-columns">
      <% @challenge.art_works.each do |a| %>
          
          <div class="card">
            <div class="card-body p-1">
              <!--< p class="text-centered"><%= image_tag a.image, class: 'd-block w-100' %><p>
              <%= link_to a.title, art_work_path(a) %> -->
                 
              <%= link_to image_tag(a.image, style:'width:100%'), challenge_art_work_path(a.challenge, a), class: 'stretched-link' %>

              
            </div>
          </div>
      <% end %>
     <div>
     
</div>