config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'sessions#home'

  get '/art_works/title' => 'art_works#title', as: 'title'

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#facebook_login'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'



  resources :art_works do
    resources :comments
  end

  resource :comments, :only => [:update, :destroy, :create]


  # resources :challenges do
  #   resources :art_works, shallow: true
  # end

  resources :challenges do
    resources :art_works
  end

  resources :users do
    resources :art_works
  end
  
end

app/models/art_work.rb
class ArtWork < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    belongs_to :challenge
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true
    validate :correct_image

    scope :title, -> {order(:title)}


    private
    def correct_image
        if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
            errors.add(:image, 'must be a JPEG or PNG.')
        elsif image.attached? == false 
            errors.add(:image, 'required.')
        end
    end

end

app/models/artwork.rb
class ArtWork < ApplicationRecord
    belongs_to :user
    belongs_to :challenge
    has_many :comments
    # has_many :users, through: :comments 
end

app/controllers/art_works_controller.rb
class ArtWorksController < ApplicationController
    before_action :redirect_if_not_logged_in, except: [:index, :show]
    before_action :set_art_work, except: [:index, :new, :create]


    def title
       
        @art_work = ArtWork.all.title
        
        
    end

    def index
        @user = User.find_by_id(params[:user_id])
        @art_works = @user.art_works    
    end

    def new
        if params[:challenge_id] && @challenge = Challenge.find_by_id(params[:challenge_id])
            @art_work = @challenge.art_works.build
        else
          @art_work = ArtWork.new  
        end
    end

    def create
        @art_work = current_user.art_works.build(art_work_params)
        if @art_work.save
            redirect_to art_work_path(@art_work)
        else
            render :new
        end
    end

    def show
    end 

    def edit
          @challenge = @art_work.challenge
        if @art_work.user_id != current_user.id 
            flash[:message] = "Oops, you can't edit this."
            redirect_to challenge_path(@challenge)
        end
    end

    def update
        if @art_work.update(art_work_params)
            redirect_to art_work_path(@art_work)
        else 
            render :edit 
        end
    end

    def destroy
        @challenge = @art_work.challenge
       
        @art_work.destroy
        redirect_to challenge_path(@challenge)
    end

    private

    def art_work_params
        params.require(:art_work).permit(:title, :challenge_id, :user_id, :social_handle, :image, :description)
    end

    def set_art_work
        @art_work = ArtWork.find_by(id: params[:id])
    end
end

app/helpers/art_works_helper.rb
module ArtWorksHelper
end

app/views/art_works/edit.html.erb
<div class="container" style="padding-top:60px; padding-bottom:60px">
  
<!--image view of current image being edited -->
  <div class="field" style="width:300px; height:auto">
    <%= link_to 'Back to Challenge', challenge_path(@art_work.challenge) %><br>
    <%= image_tag(@art_work.image, style:'width:100%') %>
  </div>
      
  <div class="form-row">
    <div class="card-body">
    <%= has_errors?(@art_work) %>
      <%= form_for(@art_work) do |f| %>

            <%= f.hidden_field :challenge_id %>
            
            <div class="form-group">
                <%= f.label :title %><br>
                <%= f.text_field :title %>
            </div>

            <div class="form-group">
                <%= f.label :description %><br>
                <%= f.text_field :description %>
            </div>

            <div class="actions">
                <%= f.submit "Submit", class: 'btn btn-primary'%>
            </div>
        
        <% end %>

    </div>
  </div>
  
</div>

app/views/art_works/index.html.erb
<div class="container" style="padding-top:60px; padding-bottom:60px">

  <% if current_user == @user %>
    <h1> My Submissions </h1>
  <% else %>
    <h1> <%= @user.first_name %>'s Submissions </h1>
  <% end %>

  <% if @art_works.empty? %>
    <h2> No submissions yet. <%= link_to "Join a challenge!", challenges_path %> </h2>

  <% else %>
  <div class="card-columns">
    <% @art_works.each do |a| %>
      <div class="card">
        <div class="card-body p-1">
          <!-- <%= image_tag(a.image, style:'width:100%') %> -->
          <!-- <%= link_to a.title, art_work_path(a), class: 'btn btn-secondary stretched-link' %> -->
          <%= link_to image_tag(a.image, style:'width:100%'), user_art_work_path(a.user, a), class: 'stretched-link' %>
        </div>
      </div><br>
    <% end %>
    </div>

  <% end %>
</div>

app/views/art_works/new.html.erb
<div class="form-row">
    <div class="card-body">

    <!-- specific to new form -->
        <h2> <%= @art_work.challenge.name %> </h2>
        <p>challenge instructions</p>
        <!--- end here -->

        <%= has_errors?(@art_work) %>
        
        <%= form_for(@art_work) do |f| %>

            <%= f.hidden_field :challenge_id %>
                
            <div class="form-group">
                <%= f.label :image %><br>
                <%= f.file_field :image %>
            </div>
            
            <div class="form-group">
                <%= f.label :title %><br>
                <%= f.text_field :title %>
            </div>

            <div class="form-group">
                <%= f.label :description %><br>
                <%= f.text_field :description %>
            </div>

            <div class="actions">
                <%= f.submit "Submit", class: 'btn btn-primary'%>
            </div>
        
        <% end %>
    </div>
</div>

app/views/art_works/show.html.erb
  
  <div class="container" style="padding-top:60px; padding-bottom:100px">

  <%= link_to 'Back to Challenge', challenge_path(@art_work.challenge) %><br>

  <!-- image view -->
    <div style="width:300px; height:auto;">
        <%= image_tag(@art_work.image, style:'width:100%') %>
    </div>

    <!-- title/author -->
    <br><h3> <%= @art_work.title %> </h3>
    <h6> By: <%= link_to @art_work.user.first_name, user_art_works_path(@art_work.user) %> </h6>
 
    <!--<br><h4>Description</h4>
    <p> <%= @art_work.description %> </p> -->
    <h6><%= link_to "Add a Comment", new_art_work_comment_path(@art_work), class: 'btn btn-primary' %></h6><br>

    <!-- edit/delete buttons -->
    <% if @art_work.user == current_user %>
    <%= link_to 'Edit Submission', edit_art_work_path(@art_work)%><br>
    <!-- <%= button_to 'delete', art_work_path(@art_work), :method => :delete %><br><br> -->
    <%= button_to 'delete', @art_work, :method => :delete %><br>
    <% end %>
    <!-- end -->
    

      <% @art_work.comments.each do |c| %> 
        <div class="card" style="width:300px">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"> 
                <b><%= c.user.first_name %></b>: <%= c.content %>

                <% if current_user && current_user == c.user || current_user == c.art_work.user %>
                <%= button_to "delete", art_work_comment_path(c.art_work,c), :method => :delete, remote: true, style:'float:right' %>
                <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    
 </div>

app/views/art_works/title.html.erb
<% @art_work.each do |a| %> 
<%= a.title %>
<% end%>