config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'sessions#home'

  get '/art_works/title' => 'art_works#title', as: 'title'

  #signup
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  # get '/auth/facebook/callback' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#facebook_login'

  #login
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout
  delete '/logout' => 'sessions#destroy'



  resources :art_works do
    resources :comments
  end

  resource :comments, :only => [:update, :destroy, :create]


  # resources :challenges do
  #   resources :art_works, shallow: true
  # end

  resources :challenges do
    resources :art_works
  end

  resources :users do
    resources :art_works
  end
  
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <div class="navbar navbar-expand-lg navbar-dark bg-dark"> -->
    <div class="navbar navbar-expand-lg" style="background-color: #f5f5f5; padding-top:40px">
      <div class="container">
        
        <%= link_to "ArtMake", root_path, class: 'navbar-brand' %>

         <ul class="navbar-nav mr-auto">
           <% if logged_in? %>
          

             <li class="nav-link">
              <%= link_to "My Submissions", user_art_works_path(current_user) %>
            </li>
           
             
           </li>
           <% end %>
           <li class="nav-link">
             <%= link_to "Challenges", challenges_path %>
           </li>
         </ul>


        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-link">
              <%= link_to "Logout", logout_path, method:"delete" %>
            </li>
          <% else %>
            <li class="nav-link">
              <%= link_to "Sign Up", signup_path %>
            </li>
            <li class="nav-link">
              <%= link_to "Log In", login_path %>
            </li>
            <% end %> 
        </ul>  
      </div>
    </div>
        <div>
          <% if flash[:message] %>
            <%= flash[:message] %>
          <% end %>
          <%= @error %>
        </div>

        <div class="container">
          <%= yield %>

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </div>
  </body>
</html>